services:
  backend:
    image: aditya53124/my-backend:latest
    ports:
      - "3000:3000"
    environment:
      # Use the full Service URI provided by Aiven
      - DATABASE_URL=postgres://avnadmin:REDACTED@pg-22cf7cca-ksolves-7209.i.aivencloud.com:18088/defaultdb?sslmode=require
      - PORT=3000

  frontend:
    image: aditya53124/my-frontend:latest
    ports:
      - "80:80"